language: python

sudo: required

matrix:
    include:
        - dist: trusty
          python: 2.6
          env: NAME=trusty-2.6
        - dist: trusty
          python: 2.7
          env: NAME=trusty-2.7
        - dist: trusty
          python: 3.3
          env: NAME=trusty-3.3

        - dist: xenial
          python: 2.7
          env: NAME=xenial-2.7
        - dist: xenial
          python: 3.4
          env: NAME=xenial-3.4
        - dist: xenial
          python: 3.5
          env: NAME=xenial-3.5
        - dist: xenial
          python: 3.6
          env: NAME=xenial-3.6
        - dist: xenial
          python: 3.7
          env: NAME=xenial-3.7

install: pip install -e .[test]

script: py.test test_pcrypt.py

notifications:
  email: false
